---
title: "Calcification (GNET)"
output: word_document
---

```{r results="hide", message=FALSE, warning=FALSE}
rm(list=ls())
setwd("/Users/alexgood/Desktop/Coral Chapter/BW & TA/TA")
library(knitr)
library(tidyverse)
library(cowplot)
library(car)
library(afex)
library(emmeans)
library(plotrix)
library(dplyr)
library(ggpubr)
library(multcomp)  #  for glht, summary of glht
library(multcompView)
library(lmtest)
library(qqplotr)
library(MuMIn)
library(ggplot2)
library(gmodels)
library(DescTools)
library(lme4)
library(vegan)
library(forcats)
library(ggsignif)
library(ggsci)
library(scales)
library(ggstatsplot)
library(rstantools)
library(nlme)
library(PMCMRplus)
library(ez)
library(ellipse)
library(dunn.test)
library(lmerTest)   # To get p-values for the lmer model
library(effectsize) # For effect size calculations
library(performance)
```

# GNET
## Gnet data
```{r}
gnet <- read.csv("/Users/alexgood/Desktop/Coral Chapter/BW & TA/TA/Gnet_Tubridity.csv")
gnet$Experiment <- as.factor(gnet$Experiment)
gnet$Timepoint <- as.factor(gnet$Timepoint)
gnet$Chamber <- as.factor(gnet$Chamber)
gnet$Treatment <- as.factor(gnet$Treatment)
gnet$Colony <- as.factor(gnet$Colony)
gnet$Coral <- as.factor(gnet$Coral)
gnet$Location <- as.factor(gnet$Location)
gnet$Turbidity <- as.numeric(gnet$Turbidity)
summary(gnet)
view(gnet)

gnet %>%
  group_by(Timepoint) %>%
  summarise(n = sum(!is.na(Turbidity)))

# Create separate Sediment and Temperature factors
gnet$Sediment <- factor(ifelse(gnet$Treatment %in% c("C", "HT"), "Control", "High"))
gnet$Temperature <- factor(ifelse(gnet$Treatment %in% c("C", "HS"), "Control", "High"))
view(gnet)

Q1 <- quantile(gnet$mo2_turb, 0.25, na.rm = TRUE)
Q3 <- quantile(gnet$mo2_turb, 0.75, na.rm = TRUE)
IQR <- Q3 - Q1

lower_bound <- Q1 - 2 * IQR
upper_bound <- Q3 + 2 * IQR
lower_bound
upper_bound

# 1. Count total rows before filtering
total_rows <- nrow(gnet)
total_rows #1723

# 2. Filter to keep only Gnet2 between -10 and 10
gnet_filtered <- gnet %>% 
  filter(
         Gnet2 >= -3 & Gnet2 <= 3)
summary(gnet_filtered)

# 3. Count rows after filtering
filtered_rows <- nrow(gnet_filtered)

# 4. Calculate how many were removed
removed_rows <- total_rows - filtered_rows
removed_rows #79

# Print the result
cat("Number of data points removed:", removed_rows, "\n")
cat("Number of data points kept:", filtered_rows, "\n")

gnet.south <- gnet_filtered[which(gnet_filtered$Location=='SB'), ]
view(gnet.south)

gnet.north <- gnet_filtered[which(gnet_filtered$Location=='NB'), ]
view(gnet.north)

gnet_summary <- gnet %>%
  group_by(Treatment, Colony) %>%
  summarise(
    mean_Gnet = mean(Gnet2, na.rm = TRUE),
    .groups = "drop"
  )
View(gnet_summary)
write.csv(gnet_summary, "Gnet_averaged_by_Treatment_Colony.csv", row.names = FALSE)

gnet.avg <- read.csv('/Users/alexgood/Desktop/Coral Chapter/BW & TA/Gnet_averaged_by_Treatment_Colony.csv')
gnet.avg$Treatment <- as.factor(gnet.avg$Treatment)
gnet.avg$Colony <- as.factor(gnet.avg$Colony)
gnet.avg$Temp <- as.factor(gnet.avg$Temp)
gnet.avg$Sed <- as.factor(gnet.avg$Sed)
gnet.avg$Location <- as.factor(gnet.avg$Location)
summary(gnet.avg)

gnet_ind <- gnet %>%
  group_by(Coral, Treatment, Colony, Location) %>%
  summarise(
    mean_Gnet = mean(Gnet2, na.rm = TRUE),
    .groups = "drop"
  )
View(gnet_ind)
write.csv(gnet_ind, "Gnet_averaged_by_Individual.csv", row.names = FALSE)

gnet.ind <- read.csv('/Users/alexgood/Desktop/Coral Chapter/BW & TA/Gnet_averaged_by_Individual.csv')
gnet.ind$Treatment <- as.factor(gnet.ind$Treatment)
gnet.ind$Colony <- as.factor(gnet.ind$Colony)
gnet.ind$Temp <- as.factor(gnet.ind$Temp)
gnet.ind$Sed <- as.factor(gnet.ind$Sed)
gnet.ind$Location <- as.factor(gnet.ind$Location)
summary(gnet.ind)
```

## Turbidity and Temp Graphs
```{r}
custom_colors <- c("#00A9CC", "#996035", "#007A99", "#662F00") 

turb_time <- ggplot(gnet, aes(x=Timepoint, y=Turbidity, fill=Treatment, color=Treatment)) + 
  geom_point(size=2) +
  theme_classic() +
  labs(y="Turbidity (NTU)", x="Timepoint") +
  geom_hline(aes(yintercept=50)) +
  geom_hline(aes(yintercept=29.1), linetype="longdash") +
  theme(legend.position = "top") +
  scale_x_discrete(limits = as.character(1:24)) +
  scale_color_manual(
  name = "Treatment",
  values = c("C" = "#00A9CC", "HS" = "#996035", HT =  "#007A99", HX = "#662F00"),
  labels = c("C" = "Control", "HS" = "High Sed", HT =  "High Temp", HX = "High S x T")
  ) +
  scale_fill_manual(
    name = "Treatment",
    values = c("C" = "#00A9CC", "HS" = "#996035", "HT" = "#007A99", "HX" = "#662F00"),
    labels = c("C" = "Control", "HS" = "High Sed", "HT" = "High Temp", "HX" = "High S x T")
  )
turb_time
save_plot("Turbidity_Time.tiff", turb_time, base_height = 6, base_width = 10)

# Calculate mean and standard error by chamber
summary <- gnet %>%
  group_by(Chamber) %>%
  summarise(
    Mean_Turbidity = mean(Turbidity, na.rm = TRUE),
    SE_Turbidity = sd(Turbidity, na.rm = TRUE) / sqrt(n()),
    Min_Turbidity = min(Turbidity, na.rm = TRUE),
    Max_Turbidity = max(Turbidity, na.rm = TRUE)
  )

# View the summary
print(summary)

turbidity <- ggplot(gnet, aes(x=Treatment, y=Turbidity)) + 
  geom_boxplot() +
  theme_classic() +
  labs(y="Turbidity (NTU)", x="") +
  geom_hline(aes(yintercept=50)) +
  geom_hline(aes(yintercept=29.1), linetype="longdash") +
  theme(legend.position = "top")
turbidity

mean_turb <- mean(gnet$Turbidity[gnet$Treatment %in% c('HS', 'HX')])
mean_turb

save_plot("Turbidity.tiff", turbidity, base_height = 3, base_width = 4)
```

```{r}
holding <- read.csv('/Users/alexgood/Desktop/Coral Chapter/MC data entry/holding tank.csv')
View(holding)
summary(holding)
summary_temp <- holding %>%
  summarise(
    mean_temp = mean(Temp, na.rm = TRUE),
    sd_temp = sd(Temp, na.rm = TRUE)
  )
summary_temp

summary_ph <- holding %>%
  summarise(
    mean_ph = mean(pH, na.rm = TRUE),
    sd_ph = sd(pH, na.rm = TRUE)
  )
summary_ph

summary_salinity <- holding %>%
  summarise(
    mean_salinity = mean(Salinity, na.rm = TRUE),
    se_salinity = sd(Salinity, na.rm = TRUE)
  )
summary_salinity

summary_do <- holding %>%
  summarise(
    mean_do = mean(DO, na.rm = TRUE),
    se_do = sd(DO, na.rm = TRUE)
  )
summary_do

env <- read.csv('/Users/alexgood/Desktop/Coral Chapter/MC data entry/MC_Environmental_Entered.csv')
View(env)
summary(env)
env$Chamber <- as.factor(env$Chamber)

summary_salinity <- env %>%
  summarise(
    mean_salinity = mean(Salinity, na.rm = TRUE),
    sd_salinity = sd(Salinity, na.rm = TRUE)
  )
summary_salinity

summary_ph <- env %>%
  summarise(
    mean_ph = mean(pH, na.rm = TRUE),
    sd_ph = sd(pH, na.rm = TRUE)
  )
summary_ph

summary_do <- env %>%
  summarise(
    mean_do = mean(DO, na.rm = TRUE),
    sd_do = sd(DO, na.rm = TRUE)
  )
summary_do

view(env)
ylab <- expression('Temperature ('*~degree*C*')')

temp <- ggplot(env, aes(x=Chamber, y=Temp..C., na.rm = TRUE)) + 
  geom_boxplot(na.rm = TRUE) +
  theme_classic() +
  labs(y=ylab) +
  geom_hline(aes(yintercept=31)) +
  geom_hline(aes(yintercept=28.64), linetype="longdash") +
  theme(axis.title.x=element_blank()) +
  scale_x_discrete(labels=c("Control", "High Sed", "High Temp", "High S x T"))
temp

mean_HTHX <- mean(env$Temp..C.[env$Chamber %in% c('3', '4')])
mean_HTHX

save_plot("Temperature.tiff", temp, base_height = 3, base_width = 4)
```

## Gnet raw data
```{r}
ylab = expression("Net Calcification" ~ "(μmol CaCO"[3]~"g"^{-1}~h^{-1}*")")
ylab2 <- expression("MO"[2]*" (mg g"^-1*" h"^-1*")")

Gnet_Treatment_location <- ggplot(gnet, aes(x=Treatment, y=Gnet2, fill=Location)) + 
  geom_boxplot() +
  theme_minimal() +
    ylim(-5,5) +
   annotate("text", x = 0.7, y = 4.5, label = "Calcification", size = 4) + 
   annotate("text", x = 0.7, y = -3.5, label = "Dissolution", size = 4) + 
  geom_hline(yintercept = 0, linetype="dashed") +
  labs(y=ylab, x="") +
  ylim(-4,4.5) +
  theme(legend.position = "top") +
  scale_fill_manual(values = c("NB" = "#D3D3D3", "SB" = "#56B4E9"),  # Adjust colors as needed
                     labels = c("NB" = "PR44", "SB" = "HIMB"))
Gnet_Treatment_location
save_plot("Gnet_Treatment_Location.tiff", Gnet_Treatment_location, base_height = 5, base_width = 8)

 ggplot(gnet, aes(x=Treatment, y=Gnet2)) + 
  geom_boxplot() +
  theme_classic() +
  labs(y=ylab, x="") +
  theme(legend.position = "top")

Gnet_colony <- ggplot(gnet, aes(x=Colony, y=Gnet2)) + 
  geom_boxplot() +
  theme_classic() +
  labs(y=ylab, x="") +
  theme(legend.position = "top")
Gnet_colony
save_plot("Gnet_Colony.tiff", Gnet_colony, base_height = 4, base_width = 6)

ggplot(gnet, aes(x=Location, y=Gnet2)) + 
  geom_boxplot() +
  theme_classic() +
  labs(y=ylab, x="") +
  theme(legend.position = "top")

Gnet_time <- ggplot(gnet, aes(x=Timepoint, y=Gnet2)) + 
  geom_boxplot() +
  theme_classic() +
  labs(y=ylab, x="") +
  theme(legend.position = "top")
Gnet_time
save_plot("Gnet_Time.tiff", Gnet_time, base_height = 5, base_width = 8)
```

## correlation
```{r}
TA_Turb_Corr <- cor(gnet$Gnet2, gnet$Turbidity, method = "spearman")
print(TA_Turb_Corr) # -0.0653063 - weak correlation

MO2_avg_Turb <- cor(gnet$mo2_turb_avg, gnet$Turbidity, method = "spearman")
print(MO2_avg_Turb) # -0.09119718 - weak correlation

MO2_Turb <- cor(gnet$mo2_turb, gnet$Turbidity, method = "spearman")
print(MO2_Turb) #  -0.081708 - weak correlation

MO2_avg_Gnet <- cor(gnet$mo2_turb_avg, gnet$Gnet2, method = "spearman")
print(MO2_avg_Gnet) #  0.02470218 - weak correlation

MO2_Gnet <- cor(gnet$mo2_turb, gnet$Gnet2, method = "spearman")
print(MO2_Gnet) # 0.02571819 - weak correlation
```

## graph Gnet and MO2 over time 
```{r}
Gnet_MO2_Time <- ggplot(gnet, aes(x = Timepoint)) +
  geom_point(aes(y = Gnet2, color = "Gnet2"), alpha = 0.2) +
  geom_point(aes(y = mo2_turb, color = "mo2_turb"), alpha = 0.5) +
  scale_y_continuous(
    name = "Variable 1",
    limits = c(-50, 50)) +
  scale_y_continuous(
    name = ylab,
    sec.axis = sec_axis(~./10, name = ylab2), limits = c(-5,5)) +
  scale_color_manual(name = "", values = c("blue", "red"), labels = c("Gnet2" = "Gnet", "mo2_turb" = "MO2")) +
  labs(title = "", x = "") +
 facet_wrap(
    ~ fct_recode(Chamber,
      "Control" = "1",
      "High Sediment" = "2",
      "High Temperature" = "3",
      "High Sediment x High Temperature" = "4"
    ),
    scales = "free"
  ) + 
  theme_classic()
Gnet_MO2_Time
save_plot("Gnet_MO2_Time.tiff", Gnet_MO2_Time, base_height = 8, base_width = 15)
```

```{r}
# -- Gnet Violin Plot --
gnet_plot <- ggplot(gnet_filtered, aes(x = as.factor(Timepoint), y = Gnet2)) +
  geom_violin(fill = "blue", alpha = 0.4, trim = FALSE) +
  geom_boxplot(width = 0.1, fill = "blue", alpha = 0.5, outlier.size = 0.5) +
  facet_wrap(~ fct_recode(Chamber,
                          "Control" = "1",
                          "High Sediment" = "2",
                          "High Temperature" = "3",
                          "High Sediment x Temperature" = "4"),
             scales = "free") +
  labs(x = "", y = ylab) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.5) +
   ylim(-3,3) +
  scale_x_discrete(limits = as.character(1:24)) +
  theme_classic()
gnet_plot

# -- MO2 Violin Plot --
mo2_plot <- ggplot(gnet_filtered, aes(x = as.factor(Timepoint), y = mo2_turb)) +
  geom_violin(fill = "red", alpha = 0.4, trim = FALSE) +
  geom_boxplot(width = 0.1, fill = "red", alpha = 0.5, outlier.size = 0.5) +
 facet_wrap(~ fct_recode(Chamber,
                          "Control" = "1",
                          "High Sediment" = "2",
                          "High Temperature" = "3",
                          "High Sediment x Temperature" = "4"),
             scales = "free") +
  ylim(-3,3) +
  scale_x_discrete(limits = as.character(1:24)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", size = 0.5) +
  labs(x = "Timepoint", y = ylab2) +
  theme_classic()
mo2_plot

# -- Save or Combine Plots --
save_plot("Gnet_Time_Violin.tiff", gnet_plot, base_height = 6, base_width = 12)
save_plot("MO2_Time_Violin.tiff", mo2_plot, base_height = 6, base_width = 12)

# OR: Combine them if you prefer side-by-side
combined <- plot_grid(gnet_plot, mo2_plot, ncol = 1, labels = c("A", "B"))
combined
save_plot("Gnet_MO2_Violins.tiff", combined, base_height = 12, base_width = 16)
```

# Assumptions
```{r}
# Linear model with fixed effects only 
model_gnet <- aov(Gnet2 ~ Treatment * Location, data = gnet_filtered)

# 1. Normlaity of residuals 
qqnorm(residuals(model_gnet)); qqline(residuals(model_gnet)) # good
#shapiro.test(residuals(model_mo2)) 

# 2. Check Homogeneity of Variances by plotting residuals vs fitted values
plot(fitted(model_gnet), residuals(model_gnet), main = "Residuals vs Fitted Values", 
     xlab = "Fitted Values", ylab = "Residuals") + abline(h = 0, col = "red")
# or 
plot(fitted(model_gnet), residuals(model_gnet)) + abline(h = 0, col = "red")
bgtest(model_gnet) # good

# Levene's test 
leveneTest(residuals(model_gnet) ~ Treatment * Location, data = gnet) # good

# Independence of residuals 
plot(residuals(model_gnet)) # good
```

# Models used
```{r}
gnet.anova <- aov(Gnet2 ~ Treatment * Location, data = gnet_filtered)
anova(gnet.anova)
print(summary(gnet.anova))
TukeyHSD(gnet.anova)

gnet.model <- lmer(Gnet2 ~ Treatment * Location + (1 | Colony) + (1 | Coral), data = gnet_filtered)
anova(gnet.model, type = 3)
summary(gnet.model)
emmeans(gnet.model, pairwise ~ Location | Treatment)
emmeans(gnet.model, pairwise ~ Treatment | Location)
emmeans(gnet.model, pairwise ~ Location * Treatment)
emmeans(gnet.model, pairwise ~ Treatment * Location)
emmeans(gnet.model, pairwise ~ Treatment)

# not sure if I need to seperate by nroth and south ...
# gnet.anova <- aov(ynpq ~ Treatment, data = south)
# anova(ynpq.anova)
# print(summary(ynpq.anova))
# TukeyHSD(ynpq.anova)
# 
# ynpq.anova <- aov(ynpq ~ Treatment, data = north)
# anova(ynpq.anova)
# print(summary(ynpq.anova))
# TukeyHSD(ynpq.anova)

# Model without Timepoint as a random effect
mod0 <- lmer(Gnet2 ~ Treatment * Location + (1 | Colony), data = gnet_filtered, REML = FALSE)

# Model with Timepoint as a random effect
mod1 <- lmer(Gnet2 ~ Treatment * Location + (1 | Timepoint) + (1 | Colony), data = gnet_filtered, REML = FALSE)

# Compare models
anova(mod0, mod1)

# Fit the mixed-effects model
model1 <- lmer(Gnet2 ~ Location * Treatment + (1 | Colony/Timepoint), data = gnet_filtered)
anova(model1)

```

# Treatment stats
```{r}
gnet.anova <- aov(Gnet2 ~ Sediment * Temperature, data = gnet_filtered)
anova(gnet.anova)
print(summary(gnet.anova))
TukeyHSD(gnet.anova)
# no significance 

gnet.anova.north <- aov(Gnet2 ~ Sediment * Temperature, data = gnet.north)
anova(gnet.anova.north)
print(summary(gnet.anova.north))
TukeyHSD(gnet.anova.north)
# no significance 

gnet.anova.south <- aov(Gnet2 ~ Sediment * Temperature, data = gnet.south)
anova(gnet.anova.south)
print(summary(gnet.anova.south))
TukeyHSD(gnet.anova.south)

# Get the least squares means (LSMs) for each combination of Temp and pH
# marginal means adjusted for the other factors in the model
gnet_lsm <- emmeans(gnet.anova.south, ~ Sediment * Temperature)
print(gnet_lsm)

```
